print ('Note : "Give only integers for calculation"')
a = int(input("Enter First number as A : "))
b = int(input("Enter Second number as B : "))
print("A = ",a)
print("B = ",b)
print (f"Sum : A + B = {a + b}")
print (f"Subtract : A - B = {a - b}")
print (f"Mutliply : A * B = {a * b}")
print (f"Division : A / B = {a / b}")
# print (f"Modulos : A % B = {a % b}")